### ISSUE TITLE
Random hick-ups when using RealSense

### ISSUE THREAD

**Issue by jhnnslmk** [vvvv/VL.Devices.RealSense#2]
We are experiencing major hickups with the RealSense implementation that render it kind of useless for our usecase at the moment. We were witnessing the same behaviour over days, regardless of the amount of cameras connected (also happens with a single cam already). One can see that the incoming data pauses for a couple frames ... it's not just the pointcloud (which you will be seeing in the videos).

Only weird thing: we have also seen it work flawlessly once or twice, but the faulty behaviour would soon come back when working in the patch (maybe after triggering a recompile) ... anyway: it's not stable.
We ruled out a general issue with RealSense though, because it works fine in the Intel RealSense Viewer 100% of the time, we could only see this happen in VL.

- Happening in beta40 VL (that's where we need it)
- Just checked with gamma 2020.2.2 as well

Running VL.Devices.RealSense.1.2.0

You can check for yourself by opening the "Visualizing the point cloud" help patch.

## Video 1
Bad video quality from on site ... I think this one is was also running gamma (you can tell by the blue help patch indicator in the top left corner), even though I'm confused the LFO shows that the entire vvvv is freezing, while this is not happening in the second video - also running gamma.
https://www.dropbox.com/s/hc8ys7950ifxi3m/Video.MOV?dl=0

## Video 2
Just recorded in gamma 2020.2.2
https://www.dropbox.com/s/xl9b1bq2645hhgr/2020-11-02%2013-59-54.mp4?dl=0

**Comment by jhnnslmk** [comment]
@azeno @joreg

**Comment by jhnnslmk** [comment]
This is how we're using it in our project.
Doesn't run in gamma because it's making use of VL.CoreLib.VVVV because of ToBufferDescription.
Bug tested against beta 40.

At first the bug didn't show, the next time I opened it, it was there right from the beginning ... when I then opened the VL editor it got worse (freeze every 3 seconds). Closing the editor again didn't make it better again.

[realsense-bug.zip](https://github.com/vvvv/VL.Devices.RealSense/files/5477263/realsense-bug.zip)

**Comment by azeno** [comment]
Had issues with Xenko/Stride when running under beta40 - I therefor backported the fix as you're using a somehow modified version anyways.

[realsense-fix-beta40.zip](https://github.com/vvvv/VL.Devices.RealSense/files/5482613/realsense-fix-beta40.zip)

**Comment by azeno** [comment]
The problem was that each camera frame a new array got allocated. That array exceeded the size of 85k bytes and therefor was considered a large object allocated on the large object heap (LOH). Allocations on the LOH trigger Gen2 garbage collections which lead to the hick-ups. Solution was to allocate a new array only when the point count grows and pack that array (whose length might be greater than the actual point count) into a `ArraySegment` (which implements `IReadOnlyList`). The signature of the node therefor stayed the same (`IObservable<IReadOnlyList<Vector3>>`) - the `HoldLatestCopy` node takes care of copying the data on to the main thread.

**Comment by jhnnslmk** [comment]
Sadly the behaviour isn't gone yet for me ... this video shows your linked fix from above on my machine with VL.Devices.RealSense 1.2.0 (so not the new 1.2.1 yet, but 1.2.0 + your mentioned fix).
It shows either right after startup or shows/gets worse when opening VL editor.
https://www.dropbox.com/s/iqlsxtqlctfu9a8/2020-11-03%2021-53-12.mp4?dl=0

I will also check Gamma + 1.2.1.

**Comment by jhnnslmk** [comment]
So ... not sure if this is of any help.
As I didn't bother to render the pointcloud in Stride and wanted to avoid Skia3d, I just created an IOBox. I didn't expect it to go smoothly, but you can observe the same rhythm to the freezes the bug is displaying.

It runs smoothy in this example though when I just access a couple single items of the List .. coincidence, or is this somehow related? Not sure what to think of this, I would expect this to be two separate problems, but the exact same rhythm threw me off.

https://www.dropbox.com/s/ycgwdc8hhufu21h/2020-11-03%2022-09-34.mp4?dl=0

**Comment by azeno** [comment]
You're right, my "fix" for beta40 wasn't a fix - didn't check properly, sorry. Here we go again:
[realsense-fix-beta40.zip](https://github.com/vvvv/VL.Devices.RealSense/files/5487461/realsense-fix-beta40.zip)

Regarding your second post - this seems to be an issue of the IO box itself. Without it I don't see memory allocations in the profiler. Will create a separate issue for it.

**Comment by jhnnslmk** [comment]
Thanks, this works for me!
I'm clearing the beta40 issue, can't test the 1.2.1 release
